### ISSUE TITLE
Bugs and wishes tracking

### ISSUE THREAD

**Issue by jfraundo251158** [jfraundo251158/jfraundo251158.github.io#1]
Please leave a message : - )

**Comment by GrimmiMeloni** [comment]
Complications would be nice, especially for percentages of charge values.

**Comment by jfraundo251158** [comment]
Hallo Michael - good idea. In a next version SolVecConMon will support one more loadpoint. Probably in a 4 weeks time. Then I will investigate how  Complications have to be implemented. Today I don't know. Then I will take a decision whether to implement it or not. Cheers, Juergen

**Comment by jfraundo251158** [comment]
Hallo Michael - with today v1.7 is available - with Complications. House Battery SoC, Loadpoint 1 and Loadpoint 2 charged kWh. Optimized Watt representation: values greater than 999 W are shown in kW. Cheers, Juergen

**Comment by StevieC121176** [comment]
very good App, complications are nice, but I miss the actual solar production power, consumption and grid export power in the complications

**Comment by jfraundo251158** [comment]
Stevie, real time values are not supported by Apple complications. It takes quite a lot time for update. That's why I haven't implemented it. And a finger tip on the complication opens the App. Cheers, Juergen
