### ISSUE TITLE
wrong Unit for 'Geladen' - kW should be kWh

### ISSUE THREAD

**Issue by CarG70** [jfraundo251158/jfraundo251158.github.io#10]
on page 4, the last point has a wrong unit. It should be kWh and not kW ![image](https://github.com/jfraundo251158/jfraundo251158.github.io/assets/84619072/3251dd19-a4b0-43f6-b7bb-408f06a8f402)

**Comment by jfraundo251158** [comment]
Hallo CarG70 - correct, will change it in next version // Cheers, Juergen
