### ISSUE TITLE
watchOS 8

### ISSUE THREAD

**Issue by martinknechtel** [jfraundo251158/jfraundo251158.github.io#3]
Hi Jürgen, spitzen Idee die App! Gibt es technische Gründe für watchOS 9 als Mindestvoraussetzung? Meine Apple Watch Series 3 kommt leider nur noch bis watchOS 8. 
Gruß
Martin

**Comment by jfraundo251158** [comment]
Hallo Martin, ich weiß es nicht. Aber vermutlich weil es auf dem aktuellen Stand von XCode, Swift und Watch OS erstellt wurde :-(

**Comment by jfraundo251158** [comment]
issue closed
