### ISSUE TITLE
App Crash in configuration tab

### ISSUE THREAD

**Issue by StevieC121176** [jfraundo251158/jfraundo251158.github.io#5]
I have an Apple Watch Ultra 2 with watchOS 10.0. The App Crashes as soon as i will change The EVCC Server in the configuration tab. The keyboard is briefly displayed, then the display turns black and no input is possible.

**Comment by jfraundo251158** [comment]
Hi Stevie - with the 2nd email you sent is the issue gone? Anyway I have no idea how to fix it since this is reported the very first time. Cheers, Juergen

**Comment by StevieC121176** [comment]
The Problem is still there. I reinstall The App, restart the Watch, but there is in chance to change the EVCC Server in the configuration tab. (Like in the Video) 
I can only try the app with the demo server


https://github.com/jfraundo251158/jfraundo251158.github.io/assets/113791299/e8f6d915-d154-4566-a773-e65085a43ec5

**Comment by jfraundo251158** [comment]
Thanks for the video clip - really a strange behavior. Till now almost 400 app downloads and 1000 updates and nobody else has reported this issue so far.
What has changed? WatchOS 10 was recently released for specific Watch models. Most likely it's a problem together with WatchOS 10.  
Unfortunately my SE Watch is running OS 9.6.3 and there is actually no 10.x available. 
Sorry - but actually no chance to debug the issue.

**Comment by StevieC121176** [comment]
Too bad, would have liked to use the app. Unfortunately, there is no way to Downgrade to watchOS 9 for a test.

**Comment by StevieC121176** [comment]
After an update to watchOS 10.1 beta3, the problem is fixed.
