### ISSUE TITLE
Komplikationen

### ISSUE THREAD

**Issue by falkkrueger** [jfraundo251158/jfraundo251158.github.io#6]
Hallo Jürgen,

ich bin total begeistert von Deinem Projekt und habe bei mir jetzt die App installiert und die Watch-App konfiguriert.

Es werden drei verschiedene Komplikationen angeboten, planst Du da noch mehr? Ich würde so gern auch die Solarproduktion oder Netz-bezug/-einspeisung sehen... Hast Du da vielleicht was geplant?

Übrigens zeigt die Batterie-Komplikation 0% an, obwohl ich in der App selbst die korrekten 100% sehe.

Viele Grüße
Falk

**Comment by jfraundo251158** [comment]
Hallo Falk,

wenn SolVecConMon keine Verbindung zum evcc Server hat, dann generiert mein Code zuerstmal ein ? und nach weiteren Verbindungs-Fehlern werden die PV Werte auf 0 gesetzt.
Da Apple's Komplikationen Eco - System sehr träge ist, dauert es dann eine gefühlte Ewigkeit bis wieder richtige Werte bei permanenter evcc Verbindung angezeigt werden. Da verhalten sich Apple's Eco-Systeme zur App und zu den Komplikationen total unterschiedlich.

Ich werde folgendes testen - von dem ich mir eine starke Verbesserung bei den Komplikationen erwarte. Im Fehlerfall werde ich den letzten Wert nicht mit ? bzw. 0 überschreiben und diese ? bzw. 0 nicht an das Komplikationen Eco-System weitergeben. Damit sollte sich das System bei erneuter evcc - Verbindung wieder rascher synchronisieren. Im Fehlerfall würde die Komplikation dann den  zuletzt erfolgreich gelesenen Wert anzeigen.

Wenn der Setup auf Raspi mit Traeffik... beruht, müssten eigentlich fast immer richtige Werte dargestellt werden, sofern die Watch via iPhone eine Verbindung zum evcc Server hat. 

Sollte es so funktionieren wie gedacht, werde ich weitere Komplikationen programmieren.

Beste Grüße,
    Juergen

**Comment by falkkrueger** [comment]
Hallo Juergen,

vielen Dank für die Antwort!

Das mit der Ewigkeit ist wohl richtig - einige Stunden später bekam ich dann doch Werte geliefert und ab da auch ab und an mal aktualisiert.

Derzeit zeigt die Batteriekomplikation 13% an, das muss ca. 10 Minuten her sein....

Ich habe meinen evcc Server über einen apache2 Server weitergeleitet.

Über weitere Komplikationen würde ich mich wirklich freuen!

Viele Grüße
Falk

**Comment by jfraundo251158** [comment]
Hallo Falk, 

die gedachten Änderungen bringen echt viel. Alle ca. 5 Minuten aktuelle Werte. Zudem gibt es 2 neue Komplikationen. Einmal zum Platzsparen auf der Watch die Zusammenfassung von Haus Battery SoC und Loadpoint 1 zu einer Komplikation - B:x% L:xkW. Ferner eine neue Komplikation mit Production (Erzeugung) und Griduse (Netzbezug) -> P:xkW G:xkW.

Habe die Version gerade an Apple App Store Connect zur Freigabe gesendet. Wird vermutlich bis Ende der Woche zum Download bereit sein.

Beste Grüße,
    Juergen

**Comment by falkkrueger** [comment]
Hallo Juergen, WOW! Ich weiss gar nicht, was ich sagen soll. Das ist absolut grossartig. Ich müsste fas dann ja per Update auf meine Systeme bekommen und freue mich riesig darauf. Ich suche seit 1 1/2 Jahren nach einer Möglichkeit, Daten der PV auf meine Uhr zu bekommen, das ist großartig. Wenn Dir sowas Spass macht hätte ich noch einen kleinen Vorschlag: wie wäre es mit einem iPhone-Widget..?Ich danke Dir sehr für Dein offenes Ohr und bleibe Deinem Projekt treu.  Viele GrüsseFalkVon meinem iPhone gesendetAm 06.03.2024 um 11:04 schrieb jfraundo251158 ***@***.***>:﻿
Hallo Falk,
die gedachten Änderungen bringen echt viel. Alle ca. 5 Minuten aktuelle Werte. Zudem gibt es 2 neue Komplikationen. Einmal zum Platzsparen auf der Watch die Zusammenfassung von Haus Battery SoC und Loadpoint 1 zu einer Komplikation - B:x% L:xkW. Ferner eine neue Komplikation mit Production (Erzeugung) und Griduse (Netzbezug) -> P:xkW G:xkW.
Habe die Version gerade an Apple App Store Connect zur Freigabe gesendet. Wird vermutlich bis Ende der Woche zum Download bereit sein.
Beste Grüße,
Juergen
