### ISSUE TITLE
User Password

### ISSUE THREAD

**Issue by anwi82** [jfraundo251158/jfraundo251158.github.io#7]
Hallo, ich hab mir die App installiert und auch die Server Adresse zu meiner evcc Home Assistant Installation eingetragen, Aber irgendwie will es nicht laden.
Was muss ich denn bei User und Passwort eingeben?

**Comment by jfraundo251158** [comment]
Hallo anwi82,

User u. Passwort sind nur notwendig bei einer Verbindung über den Traefik Server für weltweiten Zugriff.

Wenn du direkt auf den evcc Server im lokalen LAN/WLAN verbindest wird User/PW nicht ausgewertet.

Es ist dann eine Adresse wie http://IP-des-evcc-Server:7070 einzugeben, sofern evcc den Default-Port 7070 verwendet.

Beste Grüße,
     Juergen
